### ISSUE TITLE
TypeError: '>' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by aldets** [yozik04/vallox_websocket_api#22]
Hi,
Love the integration, create job. But unfortunetly started to get TypeError as of today in Home Assistant. 
Full log error:
```
2022-11-07 18:27:57.247 ERROR (MainThread) [homeassistant.components.vallox] Unexpected error fetching Vallox DataUpdateCoordinator data: '>' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
return await self.update_method()
File "/usr/src/homeassistant/homeassistant/components/vallox/__init__.py", line 190, in async_update_data
profile = await client.get_profile()
File "/usr/local/lib/python3.10/site-packages/vallox_websocket_api/vallox.py", line 140, in get_profile
if s["A_CYC_EXTRA_TIMER"] > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```
Did some google and found that Python2 it was kinda OK for an int to be < 1, but in Python3 it will throw a TypeError with both ways.
vallox_websocket_api = 2.12.0
HA Version = core-2022.11.1
Installation type = Home Assistant Supervised (supervisor-2022.10.2, agent ver. 1.2.2)
Python version = 3.10.7
Docker version = 20.10.21
OS = Raspbian GNU/Linux 11 (bullseye), armv7l. OS ver. : 5.15.33-v7l+
Ventilation Unit = Vallox 096 MV

Kind regards,
aldets

**Comment by aldets** [comment]
EDIT: It seems, that a simple OFF/ON to the ventilation unit did the trick. Now no errors are thrown and data is forwarded corrrectly.
Most likely I caused the error myself, because I tryed to tinker around with the code in a local project.

Kind regards,
aldets

**Comment by yozik04** [comment]
Great that you have resolved it yourself. I have not seen this error before and I am sure it would be reported if there was a problem.
