### ISSUE TITLE
Problem in 4.0.x version and Vallox 110

### ISSUE THREAD

**Issue by hrleinonen** [yozik04/vallox_websocket_api#52]
Hi,

I have home assistant integration for vallox-websocket-api 3.3.0 and integration works fine. Now I do migration to new server and it seems that vallox-websocket-api 4.0.x wont work anymore. I use "Reading Metrics" code to test.

Python version: Python 3.11.0rc1

Version: 3.3.0, work fine.

Version 4.0.2:

python vallox_test.py 
/home/homeassistant/vallox_test.py:12: DeprecationWarning: There is no current event loop
  asyncio.get_event_loop().run_until_complete(run())
Traceback (most recent call last):
  File "/home/homeassistant/vallox_test.py", line 12, in <module>
    asyncio.get_event_loop().run_until_complete(run())
  File "/usr/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/homeassistant/vallox_test.py", line 7, in run
    metrics = await client.fetch_metrics()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/vallox_websocket_api/client.py", line 239, in fetch_metrics
    self.data_model.calculate_offset(self.data_model.addresses[key])
  File "/srv/homeassistant/lib/python3.11/site-packages/vallox_websocket_api/data/model.py", line 128, in calculate_offset
    VlxDevConstants["RANGE_START_g_cyclone_general_info"],
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'RANGE_START_g_cyclone_general_info'

This is output for my hass:

2024-01-07 15:51:55.051 ERROR (MainThread) [homeassistant.components.vallox.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/components/vallox/config_flow.py", line 60, in async_step_user
    await validate_host(self.hass, host)
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/components/vallox/config_flow.py", line 35, in validate_host
    await client.get_info()
  File "/srv/homeassistant/lib/python3.11/site-packages/vallox_websocket_api/vallox.py", line 242, in get_info
    data = await self.fetch_metrics(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/vallox_websocket_api/client.py", line 239, in fetch_metrics
    self.data_model.calculate_offset(self.data_model.addresses[key])
  File "/srv/homeassistant/lib/python3.11/site-packages/vallox_websocket_api/data/model.py", line 128, in calculate_offset
    VlxDevConstants["RANGE_START_g_cyclone_general_info"],
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'RANGE_START_g_cyclone_general_info'

Regards,

Ville

**Comment by yozik04** [comment]
Can you please send bundle.js file that your unit provides for the web interface.
I also need your unit version.

**Comment by hrleinonen** [comment]
There is no such file than bundle.js (url: http://<ip>:8123/js/bundle.js, gives 404) and find gives only this:
/srv/homeassistant/lib/python3.11/site-packages/hass_frontend/static/polyfills/webcomponents-bundle.js

Btw my hass core version is 2024.1.2.

**Comment by yozik04** [comment]
Can you open devtools in your browser and reload the web page. See what *.js files it loads. The one which has `VlxDevConstants` text in it is the one I need.
What is firmware version of your Vallox 110?

**Comment by yozik04** [comment]
Can you open devtools in browser and reload the web page. See what *.js files it loads. The one which has VlxDevConstants is the one I need.
What is firmware version of your Vallox 110?

**Comment by yozik04** [comment]
You need to do it in your Vallox Web page, not in Home Assitant.

**Comment by hrleinonen** [comment]
Hi,

Version is 1.6, I have problem to update for never version.
JS file in in attachment.

[vallox.txt](https://github.com/yozik04/vallox_websocket_api/files/13901105/vallox.txt)

**Comment by yozik04** [comment]
What was the file name and path?

**Comment by hrleinonen** [comment]
Did you mean this http://vallox-ip-address/js/bundle.js (renamed in vallox.txt and uploaded https://github.com/yozik04/vallox_websocket_api/files/13901105/vallox.txt)?

**Comment by slovdahl** [comment]
Updating it in Home Assistant: https://github.com/home-assistant/core/pull/108109
